config/routes.rb
Rails.application.routes.draw do
  get 'creatures/index'

  get 'creatures/create'

  get 'creatures/new'

  get 'creatures/edit'

  get 'creatures/show'

  get 'creatures/update'

  get 'creatures/destroy'

  get 'main/index'

  get 'main/creatures'

  resources :creatures

end

app/models/creature.rb
class Creature < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
  end

  def create
    Creature.create creature_params
    redirect_to creatures_path
  end

  def new
    @creature = Creature.new
  end

  def edit
    @creature = Creature.find params[:id]
  end

  def show
    @creature = Creature.find params[:id]
  end

  def update
    c = Creature.find params[:id]
    c.update creature_params
    redirect_to creatures_path
  end

  def destroy
    c = Creature.find params[:id]
    c.delete
    redirect_to creatures_path
  end

  private

  def creature_params
    params.require(:creature).permit(:name, :description)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@welcome = "Welcome to my site"
  	@creature = Creature.first
  end
  
  def creatures
  	@stuff = 'Stuff'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/creatures/edit.html.erb
<div class="container">
	<div class="well">
	<h1>Edit your creature!</h1><br>
	<img src="http://33.media.tumblr.com/eb420f60dec4c53cdf004a8fcb19f757/tumblr_my7kpizjId1qcpijho2_250.gif">
	</div>
</div>


<div class="container">
	<div class="well">
		<%= bootstrap_form_for @creature do |c| %>
  		<%= c.text_area :name %>
  		<%= c.text_field :description %>

  <%= c.primary %>
<% end %>
	</div>
</div>

app/views/creatures/index.html.erb
<div class="container">
	<img src="https://cdn.tutsplus.com/vector/authors/sharon-milne/amanda_tut_yeti_final.jpg" height="500px" class="image"><br>
		<div class="row">
			<%= link_to '♥', new_creature_path, class: 'btn btn-danger' %><br>
			<h3>Create Your Monster!</h3>
		</div>
</div><br><br>
<div class="container">
	<div class="well">
		<h1>Monster House</h1><br>
		<img src="http://clipartist.net/openclipart.org/2013/September/abstract_shop_store_house_12-999px.png" height="300px"><br>
		<h3>The monsters that live here are...</h3>
</div>
</div>

<% @creatures.each do |creature| %>
<div class="container">
	<div class="well">
  			<h1><%= creature.name %></h1>
  			<p><%= creature.description %></p>

  				<%= link_to 'Show Creature', creature, class: 'btn btn-info'%>
  				<%= link_to 'Edit Creature', edit_creature_path(creature), class: 'btn btn-info'%>
  				<%= link_to 'Delete Creature', creature, class: 'btn btn-info', method: :delete %>
  		</div>
  </div>
</div>
<% end %>

app/views/creatures/new.html.erb
<div class="container">
	<div class="well">
	<h1>Create a new monster!</h1><br>
	<img src="http://33.media.tumblr.com/eb420f60dec4c53cdf004a8fcb19f757/tumblr_my7kpizjId1qcpijho2_250.gif">
	</div>
</div>

<div class="container">
	<div class="well">
		<%= bootstrap_form_for @creature do |c| %>
  			<%= c.text_field :name %>
  			<%= c.text_area :description %>

  			<%= c.primary %>
		<% end %>

	</div>
</div>

app/views/creatures/show.html.erb
<div class="container">
	<div class="well">
	<h1>Meet your monster!</h1><br>
	<img src="http://33.media.tumblr.com/eb420f60dec4c53cdf004a8fcb19f757/tumblr_my7kpizjId1qcpijho2_250.gif">
	</div>
</div>



<div class="container">
	<div class="well">
  <h3><strong>Name:</strong></h3><br>
  <%= @creature.name %>
  <h3><strong>Description:</strong></h3><br>
  <p><%= @creature.description %></p><br>

<%= link_to 'Back Home', creatures_path, class: 'btn btn-primary' %>
	</div>
</div>

app/views/creatures/update.html.erb
<h1>Creatures#update</h1>
<p>Find me in app/views/creatures/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Creatures</title>
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
 <script src="//code.jquery.com/jquery.js"></script>
 <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Amatic+SC" />
 <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>


	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top white">
  <div class="column">
    <center><h1><a href="/creatures">c r e a t u r e s</a></h1></center>
  </div>
</nav>

<nav class="navbar navbar-default navbar-static-bottom">
	<div class="column">
		A Ruby on Rails project by Haylee Nighbert
	</div>
</nav>

<%= yield %>

</body>
</html>

app/views/main/creatures.html.erb
<h1>Main#creatures</h1>
<p>Find me in app/views/main/creatures.html.erb</p>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>